version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: toskaboiler_dev
    volumes:
      - ./:/usr/src/app
      - nodemod:/usr/src/app/node_modules/
    ports:
      - 3000:3000
    container_name: toskaboiler_dev
  db:
    image: mongo:latest
    container_name: toskaboiler_db
    volumes:
      - mongodata:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


volumes:
  nodemod:
  mongodata:

