version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  test-build-deploy:
    jobs:
      - dockerhub/publish:
          requires:
            - cypress/run
          image: toska/$CIRCLE_PROJECT_REPONAME
          filters:
            branches:
              only: master