name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish toskaboiler to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toska/${{ github.event.repository.name }}:latest
          build_args: |
            BASE_PATH=/toskaboiler
            GIT_SHA=${{ github.sha }}

      - name: Publish shibboboiler to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toska/${{ github.event.repository.name }}:shibboboiler
          build_args: |
            BASE_PATH=/shibboboiler
            GIT_SHA=${{ github.sha }}